maven-build:
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean install -P all,dist -DcreateChecksum=true -Ddm4.websockets.port=9999 -DskipTests
  tags:
    - maven

  after_script:
    # - DISTDIR='/home/gitlab-runner/.m2/repository/de/deepamehta/deepamehta-distribution/5.0-SNAPSHOT'
    - DISTDIR='modules/dm4-distribution/target'
    - ZIPFILE="$( ls ${DISTDIR}/*.zip )"
    - FILENAME="$( basename ${ZIPFILE} .zip )"
    - NUNC="$( date +%F )"
    - cp ${DISTDIR}/${FILENAME}.zip /var/www/download.dmx.systems/ci/${FILENAME}_${NUNC}_${CI_PIPELINE_ID}.zip
    - ln -sf /var/www/download.dmx.systems/ci/${FILENAME}_${NUNC}_${CI_PIPELINE_ID}.zip /var/www/download.dmx.systems/ci/latest.zip

## This actualy works, but we won't need it for now.
#  artifacts:
#    paths: 
#      - modules/dm4-distribution/target/*.zip