stages:
  - build
  - deploy
  - trigger

maven-build:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: build
  tags:
    - docker
  script:
    - export MAVEN_OPTS="-Xmx512m"
    - node -v
    - npm -v
    - mvn clean test -P all,dist
  artifacts:
    paths:
      - modules/dmx-distribution/target/

maven-install:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: build
  tags:
    - docker
  script:
    - export MAVEN_OPTS="-Xmx512m"
    - mvn install -P all,dist
  artifacts:
    paths:
      - modules/dmx-distribution/target/*.zip
  dependencies:
    - maven-build
  only:
    - master
    - main

javadoc:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: build
  tags:
    - docker
  script:
    - export JAVA_HOME="/usr/lib/jvm/java-11-openjdk"
    - export MAVEN_OPTS="-Xmx512m"
    - mvn --version
    - mvn -P all javadoc:aggregate
    - zip -r target/apidocs.zip target/site/apidocs
  artifacts:
    paths:
      - target/*
  only:
    - master
    - main

publish-apidocs:
  stage: deploy
  tags:
    - shell
  script:
    - ci-publish-apidocs.sh
  dependencies:
    - javadoc
  only:
    - master
    - main

publish-snapshot:
  stage: deploy
  tags:
    - shell
  script:
    - ci-publish.sh snapshot
  dependencies:
    - maven-install
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != 'merge_request_event'

publish-release:
  stage: deploy
  tags:
    - shell
  script:
    - ci-publish.sh release
  dependencies:
    - maven-install
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TAG != null && $CI_PIPELINE_SOURCE != 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TAG != null && $CI_PIPELINE_SOURCE != 'merge_request_event'

deploy-to-gitlab-maven:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: deploy
  tags:
    - docker
  script:
    - 'mvn -Pall,gitlab-maven-deployment deploy -DskipTests=true -s /usr/local/lib/ci_settings.xml'
  only:
    - master
    - main
    - dm4

deploy-to-central:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: deploy
  tags:
    - docker
  script:
    - export MAVEN_OPTS="-Xmx512m"
    - mvn clean deploy -P release
  only:
    - tags

trigger-deb-project:
  stage: trigger
  trigger: dmx-platform/dmx-build-deb
  only:
    - master
  except:
    - tags

trigger-docker-project:
  stage: trigger
  trigger: dmx-contrib/dmx-docker
  only:
    - master
  except:
    - tags
