maven-build:
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean install -P all,dist -Dmaven.test.skip=true
  tags:
    - maven

  artifacts:
    enabled: true
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"

    