maven-build:

  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean install -P all,dist -DskipTests

  after_script:
    # - DISTDIR='/home/gitlab-runner/.m2/repository/de/deepamehta/deepamehta-distribution/5.0-SNAPSHOT'
    - DISTDIR='modules/dmx-distribution/target'
    - ZIPFILE="$( ls ${DISTDIR}/*.zip )"
    - FILENAME="$( basename ${ZIPFILE} .zip )"
    - NUNC="$( date +%F )"
    - MY_JOB_TOKEN="$(</home/gitlab-runner/.after-maven-build.token)"
    - cp ${DISTDIR}/${FILENAME}.zip /var/www/download.dmx.systems/ci/${FILENAME}_${NUNC}_${CI_PIPELINE_ID}.zip
    - ln -sf /var/www/download.dmx.systems/ci/${FILENAME}_${NUNC}_${CI_PIPELINE_ID}.zip /var/www/download.dmx.systems/ci/dmx-latest.zip
    # trigger pipeline to build new debian image for dmx platform
    - curl --request POST --form token="${MY_JOB_TOKEN}" --form ref=master https://git.dmx.systems/api/v4/projects/16/trigger/pipeline
