maven-build:
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean install -P all -Dmaven.test.skip=true
  tags:
    - dmx-standard

  artifacts:
    paths:
    - target/*.jar
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"

    