maven-build:
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean install -P all,dist -DcreateChecksum=true -Ddm4.websockets.port=9999 -DskipTests
  tags:
    - maven

  after_script:
    - DISTDIR='/home/gitlab-runner/.m2/repository/de/deepamehta/deepamehta-distribution/5.0-SNAPSHOT'
    - ZIPFILE='deepamehta-distribution-5.0-SNAPSHOT.zip'
    - NUNC="$( date +%F )"
    - cp ${DISTDIR}/${ZIPFILE} /var/www/download.dmx.systems/ci/dmx-desktop-5.0_NIGHLTY_${NUNC}_${CI_PIPELINE_ID}.zip

  artifacts:
    paths: 
      - dmx-platform/modules/dm4-distribution/target/*.zip