maven-build:
  stage: build
  script:
    - node -v
    - npm -v
    - mvn clean install -P all,dist
  artifacts:
    paths:
      - modules/dmx-distribution/target/*.zip

javadoc:
  stage: build
  script:
    - mvn -P all javadoc:aggregate
    - rsync -a --delete target/site/apidocs/ /var/www/apidocs.dmx.systems/apidocs/

copy-ci-and-deploy:
  stage: deploy
  dependencies:
    - maven-build
  script:
    - DISTDIR='modules/dmx-distribution/target'
    - ZIPFILE="$( ls ${DISTDIR}/dmx-*.zip )"
    - echo "ZIPFILE = ${ZIPFILE}"
    - FILENAME="$( basename ${ZIPFILE} .zip )"
    - NUNC="$( date +%F )"
    - MY_JOB_TOKEN="$(</home/gitlab-runner/.after-maven-build.token)"
    - cp ${ZIPFILE} /var/www/download.dmx.systems/ci/${FILENAME}_${NUNC}_${CI_PIPELINE_ID}.zip
    - ln -sf /var/www/download.dmx.systems/ci/${FILENAME}_${NUNC}_${CI_PIPELINE_ID}.zip /var/www/download.dmx.systems/ci/dmx-latest.zip
    ## trigger `dmx-build-deb` pipeline
    - curl -s -X POST -F token="${MY_JOB_TOKEN}" -F ref=master https://git.dmx.systems/api/v4/projects/16/trigger/pipeline >/dev/null
  only:
    - master

copy-release:
  stage: deploy
  dependencies:
    - maven-build
  script:
    - DISTDIR='modules/dmx-distribution/target'
    - ZIPFILE="$( ls ${DISTDIR}/dmx-*.zip )"
    - echo "ZIPFILE = ${ZIPFILE}"
    - cp ${ZIPFILE} /var/www/download.dmx.systems/dmx-${CI_COMMIT_TAG}.zip
  only:
    - tags

deploy-to-central:
  stage: deploy
  script:
    - mvn clean deploy -P release
  only:
    - tags

trigger-project:
  stage: deploy
  trigger: dmx-contrib/dmx-docker
  only:
    - master
  except:
    - tags
